development:
  dialect: postgres
  database: project-backend_development
  user: postgres
  password: 12345
  host: 172.28.1.2
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@172.28.1.2:5432/project-backend_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@172.28.1.2:5432/project-backend_production?sslmode=disable"}}
