version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-backend
    image: carrot123/go-buffalo:1.0
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./project-backend:/go/src/github.com/lart2000/project-backend
    #command: [ "sh", "-c", "cd /go/src/github.com/lart2000/coreabeautyperu/project-backend buffalo dev" ] 
    networks:
      backend:
        ipv4_address: 172.28.1.1
    tty: 'true'
  # web-frontend:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile-frontend
  #   restart: always
  #   volumes:
  #     - ./project-frontend/nextjs-init:/home/node/project-frontend
  #   ports:
  #     - "4000:3000"
  #   image: carrot123/nextjs-frontend
  #   restart: always
  #   command: [ "sh", "-c", "cd /home/node/project-frontend && npm install && npm run dev " ] 
  #   networks:
  #     - frontend
  #   tty: 'true'
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
    networks:
      backend:
        ipv4_address: 172.28.1.2


  # pg-admin:
  #   image: dpage/pgadmin4:latest
  #   restart: always
  #   ports:
  #     - "80:80"
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@domain.com
  #     - PGADMIN_DEFAULT_PASSWORD=12345
  #   networks:
  #     - backend
networks:
#   frontend:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16